name: PSI Audit
on: 
  push:
    branches:
    - main

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        id: psi
        with:
          url: "http://sweltering-bells.surge.sh/"
          threshold: 70
          strategy: mobile
          key: ${{ secrets.APIKEY }}